<style>
    .gu {
        align-items: center;
        background-color: #8BB860;
        border-radius: 10px;
        display: flex;
        flex-wrap: wrap;
        float: left;
        justify-content: space-arround;
        text-align: center;
        width: 100%;
        margin-top: 10px;
        margin-right: 10px;
    }

    .gu_img {

    }

    .gu_name {
        color: white;
        width: 60%;
    }

    .gu_table {
        border: 0;
        margin: 0 0 20px 20px;
        padding: 5px;
        text-align: left;
        width: 300px;
    }
</style>

<div class="gu">
    <img
        class='gu_img'
        src='tools/guichetunique/presentation/images/picto-guichet-unique.png'
        alt='Logo Guichet Unique'
    />
    <h2 class="gu_name"><?php print($data); ?></h2>
    <table class="gu_table">
        <tr>
            <td>Tél. : </td>
            <td>7777</td>
        </tr>
        <tr>
            <td>Pidgin : </td>
            <td>guichet-unique</td>
        </tr>
        <tr>
            <td>Mail : </td>
            <td>
                <a href="mailto:florac-guichet-unique@supagro.fr">
                    florac-guichet-unique@supagro.fr
                </a>
            </td>
        </tr>
    </table>
</div>
