<div class="gu">
    <img 
        class='gu_img'
        src='tools/yeswiki-tool-guichetunique/presentation/images/picto-guichet-unique.png'
        alt='Logo Guichet Unique'
    />
    <h2 class="gu_name"><?php print($data); ?></h2>
    <table class="gu_table">
        <tr>
            <td>Tél. : </td>
            <td>7777</td>
        </tr>
        <tr>
            <td>Pidgin : </td>
            <td>guichet-unique</td>
        </tr>
        <tr>
            <td>Mail : </td>
            <td>
                <a href="mailto:florac-guichet-unique@supagro.fr">
                    florac-guichet-unique@supagro.fr
                </a>
            </td>
        </tr>
    </table>
</div>
